[images]
  remote_images = ["https://ext.same-assets.com/**"]

[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NEXT_PRIVATE_TARGET = "server"
  NEXT_USE_TURBOPACK = "1"
  NODE_VERSION = "20"

[dev]
  command = "bun run dev"
  targetPort = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs"
